<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?=$title?></title>
  <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
<nav id="logged-out-nav">
  <a href="" data-template="home">Home</a>
  <a href="" data-template="register">Register</a>
  <a href="" data-template="users">Users</a>
  <a href="" data-template="login">Login</a>

</nav>
<nav id="logged-in-nav">
  <a href="" data-template="home">Home</a>
  <a href="" data-template="userEntries">My Entries</a>
  <a href="" data-template="users">Users</a>
  <a href="" data-template="logout">Logout</a>
  <input type="text" name="search" id="search" placeholder="Search..">
</nav>
<?php

  require __DIR__ . "/templates/home-template.phtml";
  require __DIR__ . "/templates/search-template.phtml";
  require __DIR__ . "/templates/login-template.phtml";
  require __DIR__ . "/templates/register-template.phtml";
  require __DIR__ . "/templates/user-entries-template.phtml";
  require __DIR__ . "/templates/full-entry-template.phtml";
  require __DIR__ . "/templates/users-template.phtml";

?>
<div class="container">  
  <header>
    <h1 class="logo"><?=$title?></h1>
  </header> 
  <main>
    <!-- INNEHÅLL -->
  </main>
</div>
  <script type="text/javascript" src="main.js"></script>
</body>
</html>
