<template id="register-template">

<h2>Register</h2>
<form id="register-form">
    <label for="username">Username</label>
    <input type="text" name="username" id="username" autocomplete="off">
    <label for="password">Password</label>
    <input type="password" name="password" id="password" autocomplete="off">
    <input type="submit" value="Register">
</form>

<p id="register-msg" class="hidden"></p>

</template>