<template id="register-template">

<h2>Register</h2>
<form id="register-form">
    <label for="username">Username</label>
    <input type="text" name="username" id="username">
    <label for="password">Password</label>
    <input type="password" name="password" id="password">
    <label for="password-repeat">Repeat Password</label>
    <input type="password" name="password-repeat" id="password-repeat">
    <input type="submit" value="Login">
</form>

</template>